name: Build EeveeSpotifyReborn

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install ldid make
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Build tweak
        run: |
          export THEOS=$HOME/theos
          make package

      - name: Convert .deb to .ipa
        run: |
          mkdir Payload
          dpkg -x ./packages/*.deb Payload
          mkdir -p Payload/Spotify.app
          mv Payload/Applications/* Payload/Spotify.app/
          zip -r EeveeSpotifyReborn.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: EeveeSpotifyReborn-ipa
          path: EeveeSpotifyReborn.ipa
